name: Network Device Testing

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'pod/**'
      - 'examples/network_testing/**'
      - 'tests/**'
      - '.github/workflows/network-testing.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'pod/**'
      - 'examples/network_testing/**'
      - 'tests/**'
      - '.github/workflows/network-testing.yml'
  workflow_dispatch:
    inputs:
      max_containers:
        description: 'Maximum containers to test'
        required: false
        default: '8'
      vlan_count:
        description: 'Number of VLANs to test'
        required: false
        default: '3'

jobs:
  network-capacity-test:
    name: Container Capacity & Network Testing
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        test-scenario:
          - name: "small-scale"
            containers: 6
            vlans: 2
            duration: 5
          - name: "medium-scale"
            containers: 12
            vlans: 3
            duration: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bridge-utils iproute2 iputils-ping
          
      - name: Load VLAN kernel module
        run: |
          sudo modprobe 8021q
          lsmod | grep 8021q
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov pyyaml
          
      - name: Run unit tests first
        run: |
          python -m pytest tests/unit/ -v --tb=short
          
      - name: Verify Docker setup
        run: |
          docker --version
          docker run --rm --privileged busybox echo "Docker privileged test passed"
          
      - name: Run network testing quick demo
        timeout-minutes: 10
        run: |
          cd examples/network_testing
          python quick_test.py
        continue-on-error: true
        
      - name: Run container capacity test
        timeout-minutes: 15
        run: |
          cd examples/network_testing
          python container_capacity_test.py \
            --max-containers ${{ matrix.test-scenario.containers }} \
            --vlan-count ${{ matrix.test-scenario.vlans }} \
            --test-duration ${{ matrix.test-scenario.duration }} \
            --max-concurrent 3 \
            --output "capacity_test_${{ matrix.test-scenario.name }}_py${{ matrix.python-version }}.json" \
            --verbose
        continue-on-error: true
        
      - name: Generate network device test config
        run: |
          cd examples/network_testing
          python network_device_test_framework.py --create-sample
          
      - name: Run network device scenario tests
        timeout-minutes: 10
        run: |
          cd examples/network_testing
          python network_device_test_framework.py \
            --config sample_network_test_config.yaml \
            --output "device_test_${{ matrix.test-scenario.name }}_py${{ matrix.python-version }}.json" \
            --verbose
        continue-on-error: true
        
      - name: Collect system information
        if: always()
        run: |
          echo "=== System Information ===" > system_info.txt
          uname -a >> system_info.txt
          docker --version >> system_info.txt
          python --version >> system_info.txt
          lsmod | grep 8021q >> system_info.txt
          echo "=== Network Interfaces ===" >> system_info.txt
          ip link show >> system_info.txt
          echo "=== Docker Networks ===" >> system_info.txt
          docker network ls >> system_info.txt || true
          echo "=== Container Status ===" >> system_info.txt
          docker ps -a --filter "name=pod-test" >> system_info.txt || true
          
      - name: Clean up test containers
        if: always()
        run: |
          docker ps -aq --filter "name=pod-test" | xargs -r docker rm -f
          docker ps -aq --filter "name=vlan" | xargs -r docker rm -f
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: network-test-results-${{ matrix.test-scenario.name }}-py${{ matrix.python-version }}
          path: |
            examples/network_testing/*.json
            examples/network_testing/*.yaml
            system_info.txt
          retention-days: 30
          
      - name: Generate test summary
        if: always()
        run: |
          cd examples/network_testing
          echo "# Network Testing Results - ${{ matrix.test-scenario.name }} (Python ${{ matrix.python-version }})" > test_summary.md
          echo "" >> test_summary.md
          echo "## Test Configuration" >> test_summary.md
          echo "- Containers: ${{ matrix.test-scenario.containers }}" >> test_summary.md
          echo "- VLANs: ${{ matrix.test-scenario.vlans }}" >> test_summary.md
          echo "- Duration: ${{ matrix.test-scenario.duration }}s" >> test_summary.md
          echo "- Python: ${{ matrix.python-version }}" >> test_summary.md
          echo "" >> test_summary.md
          echo "## Results Files" >> test_summary.md
          ls -la *.json 2>/dev/null | awk '{print "- " $9 " (" $5 " bytes)"}' >> test_summary.md || echo "No result files generated" >> test_summary.md
          
      - name: Comment test results on PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && always()
        with:
          script: |
            const fs = require('fs');
            const path = './examples/network_testing/test_summary.md';
            if (fs.existsSync(path)) {
              const summary = fs.readFileSync(path, 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🌐 Network Testing Results\n\n${summary}`
              });
            }

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: network-capacity-test
    if: always()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bridge-utils iproute2
          sudo modprobe 8021q
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov
          
      - name: Run integration tests
        run: |
          python -m pytest tests/integration/ -v --tb=short
          
      - name: Run full test suite with coverage
        run: |
          python -m pytest tests/ --cov=pod --cov-report=html --cov-report=term-missing
          
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: htmlcov/
          retention-days: 30

  security-scan:
    name: Security & Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          
      - name: Run Bandit security scan
        run: |
          # Only fail on medium/high severity issues for infrastructure tools
          bandit -r pod/ examples/ -f json -o bandit-report.json || true
          bandit -r pod/ examples/ -f txt --severity-level medium || echo "Only low-severity issues found"
          
      - name: Check dependencies for vulnerabilities
        run: |
          safety check --json --output safety-report.json || true
          safety check
          
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
          retention-days: 90